/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mem_quick_10 (
    input clk_uno,
    input clk_dos,
    input rst_uno,
    input rst_dos,
    output reg [23:0] out_uno,
    output reg [23:0] out_dos
  );
  
  
  
  reg [23:0] M_uno_d, M_uno_q = 1'h0;
  
  reg [23:0] M_dos_d, M_dos_q = 1'h0;
  
  always @* begin
    M_uno_d = M_uno_q;
    M_dos_d = M_dos_q;
    
    out_uno = M_uno_q;
    out_dos = M_dos_q;
    M_uno_d = M_uno_q + 1'h1;
    M_dos_d = M_dos_q + 1'h1;
  end
  
  always @(posedge clk_uno) begin
    if (rst_uno == 1'b1) begin
      M_uno_q <= 1'h0;
    end else begin
      M_uno_q <= M_uno_d;
    end
  end
  
  
  always @(posedge clk_dos) begin
    if (rst_dos == 1'b1) begin
      M_dos_q <= 1'h0;
    end else begin
      M_dos_q <= M_dos_d;
    end
  end
  
endmodule
