/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sensor_8 (
    input enb1,
    input enb2,
    output reg out,
    output reg out2
  );
  
  
  
  wire [1-1:0] M_ro1_out;
  ro_11 ro1 (
    .enable(enb1),
    .out(M_ro1_out)
  );
  
  wire [1-1:0] M_ro11_out;
  ro_11 ro11 (
    .enable(enb2),
    .out(M_ro11_out)
  );
  
  always @* begin
    out = M_ro1_out;
    out2 = M_ro11_out;
  end
endmodule
