/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module enb_spliter_13 (
    input enb,
    output reg enb1,
    output reg enb2,
    output reg enb3,
    output reg enb4,
    output reg enb5,
    output reg enb6,
    output reg enb7,
    output reg enb8
  );
  
  
  
  always @* begin
    enb1 = enb;
    enb2 = enb;
    enb3 = enb;
    enb4 = enb;
    enb5 = enb;
    enb6 = enb;
    enb7 = enb;
    enb8 = enb;
  end
endmodule
